
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sre-demo-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sre-demo
  template:
    metadata:
      labels:
        app: sre-demo
    spec:
      containers:
      - name: app
        image: nginx:latest
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: { duration: 300 }
      - setWeight: 50
      - pause: { duration: 300 }
      - setWeight: 100
